---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgByLSy4IW/ow3AdyUNjKfWWPTvriOhtJ9aZrhzm+VCAJBZNcUPLJubtqdOGmWnhcGiiGUO8haDTE4LDv6qJayq2AB7RvpAEE6TsupdjvC9BbwZ7yQo2GZdyO2rSDX+FLERjgY9xdBmfG1lrN29/6/KPDpiwNo/u93Pqh+F1AOgvLC0Sm+nsbEJ3i2M62yr1EUUdeXvNluKhZtyoxyQLC0gfv0Z3lgKloQao/Pash+CwD6sjWHKZ1RvX8kdjJvNJiZVke4hCS42DgrpH/W7VprQoJzi2dF/Tk3Sb0Fwrbi+v41z9lax2xrPor+gCuiD2huE1U3h1Iqjwe7zV3ucwbaYlSF2/qbxUvYNpYOQYSwMX8KUeOidbOr6H89CDkI3ifH6Gs9ICrscwcInX1L09MuapHFY7YNh/YRyHqFcsTs8LJKFlz4QR6j+7R0P4+SQkCfTviJoUt2Qx7isnwQWmgyLmoJ6nu+7gk7U9PfQvhqpRz3IRYm8ErvjoBSETUEuIrwdwbR3vXtZLsK3T9zshY8Dt36HKkcZMTeIok/MExK+sxaJK4fRCv1LpMOmjSpXacrlexZZl6Hwt1SoLaqscH+SLzk/VRScb5xqm7LNaydk2Wxuc/c1G4vUFEgTlYZ0P79D6EYPPM76CkQ+UswjuMLjyhCZKRCzJVxdXMk/O3VaWlf9c9h5fD3BH2nJNAY+X5QeNGZrDXQMsjeaQ/oMy3tPc3DjLwbtdSQ==
    username: AgBR8eYgi/IE/v3Eg4L/+GEANdgwu5ZtGI6g0l2uVpnm1fuYkjYvqu5GmQPuEkdOpPZp2ux1Lf/yDwezItq6MJdq5R5SA/7TAMrETTv9nhu4OQ2gwWKcDLUZ7AJBVTSRSTVnZszYnHDaT7SkLxLlBZ15kKCQGqYfWeMRBb0maoH87ZnvumNsHODJDObM5cp72hHxlNbP0Dm7vCzc+UyCc+Zt2eEzU5qQ8v8uIbeDqHihCF32LWU1Uh9c11R/6cIEgd5yi6yfcGrQrME+iDMhNNe7Q6WckGPMIMFjbWL/f1TXvWLBXYirdgvfMrgN+Zi9GeAetINQmpaGHRkyQCgrPnFXQC8D2qcCNzGl7eg5pfr96nZmajXm6Iq8oHQcATyoah8bR8DEJR/cVg89eRVjkKQSvWvUprKK3UsSzN5CyfwmU8Asyslci/qjd0BuG/9H18AtPTo5RWXMzhy0AtUDD7soVnyUglJIsKub6Tx32G/PVSui4AR/d5Z5zUl7W3ah7Z/HWWAy0vNuMWVPqX8tPfY1trR2Y61D8S72P//KTJDy0eyEQqCwclr7oCDUtX5PPAQ3PL1tSXOY9MteCd3DL+fisHO1gpmAY2IHjJNaHsCKmyTF+V9LoN5Xl5IYJcRjmJHDVNDEObiY/QtlWpqPbYZu5fNyvxydc4mGN2aZAOwCZ6T4wtns32wvJXDJ0v3r2qsWpBTsMw==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
